### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [Fortune117/DiscreteTTTAddons#1]
I wanted to know, mistakes are accepted, or you posted, but if a lot is not working, it is our problem or you would like to work and can you tell me where that doesn't work or throws an error.

**Comment by Fortune117** [comment]
I honestly don't understand what you're trying to ask

**Comment by Fortuneisfatlol** [comment]
dok441 your sentences is a non sentence. It is grammatically and syntactically incorrect. Try to use more fullstops and less commas next time

**Comment by dok441** [comment]
I translate through the translator, I know the power of native language is Russian, understand me. I ask, if I write errors in the scripts or if something doesn't work, you will fix it? Just a thread on facepunh you wrote that is the old your works and spread in public access, but will you fix errors if they are not talking, so wanted to clarify, if you make mistakes you fix them?

**Comment by Heyter** [comment]
Я так орнул. Я уже весь код переписал и у меня все прекрасно работает.

**Comment by dok441** [comment]
Да всем насрать....
